import { Header, Footer } from "@/components"
import { Card } from "@/components/ui"

export const metadata = {
  title: "Terms of Service | Resume Bullet Generator",
  description: "Terms of Service for Resume Bullet Generator",
}

export default function TermsOfServicePage() {
  return (
    <>
      <Header />
      <main className="container mx-auto px-4 py-12">
        <Card className="max-w-4xl mx-auto prose prose-gray dark:prose-invert">
          <h1>Terms of Service</h1>
          <p className="text-sm text-gray-500">Last updated: January 2025</p>

          <p>
            These Terms of Service (&quot;Terms&quot;) govern your use of the
            Resume Bullet Generator website and service (the
            &quot;Service&quot;) operated by Pariwesh Tamrakar (&quot;we&quot;,
            &quot;our&quot;, or &quot;us&quot;) from New South Wales, Australia.
          </p>

          <p>
            By accessing or using the Service, you agree to be bound by these
            Terms. If you disagree with any part of the Terms, you may not
            access the Service.
          </p>

          <h2>1. Description of Service</h2>
          <p>
            Resume Bullet Generator is an AI-powered tool that helps users
            create professional resume bullet points. Users input job
            descriptions and their professional experience, and our Service uses
            artificial intelligence to generate tailored, quantified resume
            bullet points.
          </p>

          <h3>1.1 AI-Generated Content Disclosure</h3>
          <p>
            <strong>Important:</strong> The resume bullet points generated by
            our Service are created using artificial intelligence technology
            (OpenAI GPT). While we strive to produce high-quality, relevant
            content, the output is machine-generated and should be reviewed and
            edited by you before use. We do not guarantee that AI-generated
            content will be error-free, perfectly accurate, or suitable for any
            specific purpose.
          </p>

          <h2>2. Eligibility</h2>
          <p>
            You must be at least 16 years old to use this Service. By using the
            Service, you represent and warrant that you are at least 16 years of
            age and have the legal capacity to enter into these Terms.
          </p>

          <h2>3. Account and License</h2>

          <h3>3.1 Free Tier</h3>
          <p>
            We offer a free tier that allows 3 resume bullet generations per
            day. Free tier usage is tracked by IP address and resets every 24
            hours. No account or registration is required for the free tier.
          </p>

          <h3>3.2 Paid Licenses</h3>
          <p>We offer the following paid license options:</p>
          <ul>
            <li>
              <strong>Basic License (A$15):</strong> One-time payment for 50
              resume bullet generations. Generations never expire.
            </li>
            <li>
              <strong>Lifetime License (A$29):</strong> One-time payment for
              unlimited resume bullet generations forever.
            </li>
          </ul>

          <h3>3.3 License Key</h3>
          <p>
            Upon purchase, you will receive a unique license key via email from
            our payment processor, LemonSqueezy. You are responsible for keeping
            your license key secure. You may use your license key on multiple
            devices and browsers. Do not share your license key publicly.
          </p>

          <h2>4. Acceptable Use</h2>
          <p>You agree not to use the Service to:</p>
          <ul>
            <li>
              Generate content that is illegal, harmful, threatening, abusive,
              defamatory, or otherwise objectionable
            </li>
            <li>
              Impersonate any person or entity or falsely represent your
              affiliation with any person or entity
            </li>
            <li>Generate misleading or fraudulent resume content</li>
            <li>Attempt to circumvent usage limits or access restrictions</li>
            <li>Interfere with or disrupt the Service or servers</li>
            <li>
              Use automated systems (bots, scrapers) to access the Service
              without permission
            </li>
            <li>
              Resell, redistribute, or commercialise the Service without our
              express written consent
            </li>
            <li>
              Reverse engineer or attempt to extract the source code of the
              Service
            </li>
          </ul>

          <h2>5. Intellectual Property</h2>

          <h3>5.1 Our Content</h3>
          <p>
            The Service, including its design, features, and underlying
            technology, is owned by us and protected by copyright, trademark,
            and other intellectual property laws. You may not copy, modify,
            distribute, or create derivative works based on our Service without
            our express written permission.
          </p>

          <h3>5.2 Your Content</h3>
          <p>
            You retain all rights to the job descriptions and experience
            information you input into the Service. By using the Service, you
            grant us a limited, non-exclusive license to process your content
            solely for the purpose of providing the Service to you.
          </p>

          <h3>5.3 Generated Content</h3>
          <p>
            You own the resume bullet points generated for you by the Service
            and may use them for any lawful purpose, including in your actual
            resume and job applications. We do not claim ownership of the
            generated content.
          </p>

          <h2>6. Payment Terms</h2>

          <h3>6.1 Pricing</h3>
          <p>
            All prices are listed in Australian Dollars (AUD) and include
            applicable taxes where required. We reserve the right to change our
            pricing at any time, but changes will not affect existing purchased
            licenses.
          </p>

          <h3>6.2 Payment Processing</h3>
          <p>
            Payments are processed securely by LemonSqueezy, our third-party
            payment processor. By making a purchase, you also agree to
            LemonSqueezy&apos;s{" "}
            <a
              href="https://www.lemonsqueezy.com/terms"
              target="_blank"
              rel="noopener noreferrer"
            >
              Terms of Service
            </a>
            . LemonSqueezy acts as the Merchant of Record for all transactions.
          </p>

          <h3>6.3 No Recurring Charges</h3>
          <p>
            Our licenses are one-time purchases. There are no subscriptions or
            recurring charges. Once you purchase a license, you will not be
            charged again.
          </p>

          <h2>7. Refund Policy</h2>
          <p>
            We offer refunds under the following conditions. Please also see our
            separate <a href="/refund">Refund Policy</a> for complete details.
          </p>
          <ul>
            <li>
              <strong>Refund Window:</strong> Refund requests must be made
              within 7 days of purchase.
            </li>
            <li>
              <strong>Eligibility:</strong> Refunds are provided if the Service
              does not work as described or you experience technical issues that
              prevent you from using the Service and we are unable to resolve
              them.
            </li>
            <li>
              <strong>How to Request:</strong> Contact us at{" "}
              <a href="mailto:pariweshhtamrakar@gmail.com">
                pariweshhtamrakar@gmail.com
              </a>{" "}
              with your order details and a description of the issue.
            </li>
          </ul>

          <h2>8. Disclaimers</h2>

          <h3>8.1 Service Provided &quot;As Is&quot;</h3>
          <p>
            THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS
            AVAILABLE&quot; BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS
            OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF
            MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
            NON-INFRINGEMENT.
          </p>

          <h3>8.2 No Guarantee of Results</h3>
          <p>
            We do not guarantee that using our Service will result in job
            interviews, job offers, or employment. The effectiveness of resume
            content depends on many factors outside our control, including job
            market conditions, employer preferences, and your qualifications.
          </p>

          <h3>8.3 AI Limitations</h3>
          <p>
            Our AI-powered Service may occasionally produce content that is
            inaccurate, inappropriate, or not perfectly tailored to your
            situation. You are responsible for reviewing and editing all
            generated content before use. We recommend having a human review any
            resume before submitting it to potential employers.
          </p>

          <h3>8.4 Service Availability</h3>
          <p>
            We strive to maintain high availability but do not guarantee
            uninterrupted access to the Service. The Service may be temporarily
            unavailable due to maintenance, updates, or circumstances beyond our
            control.
          </p>

          <h2>9. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL
            WE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
            OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER
            INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL,
            OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
          </p>
          <ul>
            <li>Your use or inability to use the Service</li>
            <li>Any content generated by the Service</li>
            <li>Unauthorised access to or alteration of your data</li>
            <li>Any third-party conduct on the Service</li>
          </ul>
          <p>
            OUR TOTAL LIABILITY FOR ANY CLAIMS ARISING FROM OR RELATED TO THESE
            TERMS OR THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN
            THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
          </p>

          <h2>10. Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless Resume Bullet
            Generator, its operators, and affiliates from and against any
            claims, liabilities, damages, losses, and expenses, including
            reasonable legal fees, arising out of or in any way connected with
            your access to or use of the Service, your violation of these Terms,
            or your violation of any rights of any third party.
          </p>

          <h2>11. Australian Consumer Law</h2>
          <p>
            Nothing in these Terms excludes, restricts, or modifies any consumer
            guarantee, right, or remedy conferred on you by the Australian
            Consumer Law (Schedule 2 of the Competition and Consumer Act 2010
            (Cth)) or any other applicable law that cannot be excluded,
            restricted, or modified by agreement.
          </p>

          <h2>12. Termination</h2>
          <p>
            We may terminate or suspend your access to the Service immediately,
            without prior notice, if you breach these Terms. Upon termination,
            your right to use the Service will immediately cease. For paid
            licenses, if we terminate your access due to your breach, you will
            not be entitled to a refund.
          </p>

          <h2>13. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will
            provide notice of significant changes by posting the updated Terms
            on this page with a new &quot;Last updated&quot; date. Your
            continued use of the Service after any changes constitutes
            acceptance of the new Terms.
          </p>

          <h2>14. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with
            the laws of New South Wales, Australia, without regard to its
            conflict of law provisions. Any disputes arising from these Terms
            shall be subject to the exclusive jurisdiction of the courts of New
            South Wales, Australia.
          </p>

          <h2>15. Severability</h2>
          <p>
            If any provision of these Terms is found to be unenforceable or
            invalid, that provision shall be limited or eliminated to the
            minimum extent necessary so that these Terms shall otherwise remain
            in full force and effect.
          </p>

          <h2>16. Entire Agreement</h2>
          <p>
            These Terms, together with our Privacy Policy and Refund Policy,
            constitute the entire agreement between you and us regarding the
            Service and supersede any prior agreements.
          </p>

          <h2>17. Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us:</p>
          <ul>
            <li>
              <strong>Email:</strong>{" "}
              <a href="mailto:pariweshhtamrakar@gmail.com">
                pariweshhtamrakar@gmail.com
              </a>
            </li>
            <li>
              <strong>Location:</strong> New South Wales, Australia
            </li>
          </ul>
        </Card>
      </main>
      <Footer />
    </>
  )
}
